#!/bin/bash

folderPath=$1
comment="$2"

echo "commit files"

cd ~/${folderPath}

if [ ! -n "$comment" ]; then
    comment=$(date +"%Y/%m/%d %H:%M:%S");
fi

git add .
git commit -m "${comment}"
git push
