#!/bin/bash

folderPath=$1
sourceFolder=$2
distFolder=$3

echo "make dist"

cd ~/${folderPath}/${distFolder}
rm -f *

for fileKind in css html ts_compiled gas_compiled
do
    cd ~/${folderPath}/${sourceFolder}/${fileKind}
    for file in $(ls)
    do
        if [[ ${file} != *.*.map ]]; then
            originalFile=~/${folderPath}/${sourceFolder}/${fileKind}/${file}
            case ${fileKind} in
                css )
                    newFile=~/${folderPath}/${distFolder}/${fileKind}_${file/.css/.html}
                    ;;
                ts_compiled )
                    newFile=~/${folderPath}/${distFolder}/js_${file/.js/.html}
                    ;;
                gas_compiled )
                    newFile=~/${folderPath}/${distFolder}/gas_${file}
                    ;;
                *)
                    newFile=~/${folderPath}/${distFolder}/${fileKind}_${file}
                    ;;
            esac

            cp -f ${originalFile} ${newFile}

            case ${fileKind} in
                ts_compiled )
                    echo -e "\n</script>" >> ${newFile}
                    sed -i -e "1i <script>" ${newFile}
                    ;;
                css )
                    echo -e "\n</style>" >> ${newFile}
                    sed -i -e "1i <style>" ${newFile}
                    ;;
            esac
        fi
    done
done
