#!/bin/bash

folderPath=$1
sourceFolder=$2

inputFolder=${sourceFolder}"/ts"
outputFolder=${sourceFolder}"/ts_compiled"

echo "compile typescript files"

cd ~/${folderPath}/${outputFolder}
rm -f *

cd ~/${folderPath}

tsc ./${inputFolder}/* --outDir ./${outputFolder}  --jsx react

cd ~