#!/bin/bash

folderPath=$1

sourceFolder=${folderPath}"/ts"
outputFolder=${folderPath}"/ts_compiled"

echo "compile typescript files"

cd ~/${folderPath}/${outputFolder}
rm -f *

cd ~/${folderPath}

tsc ./${sourceFolder}/* --outDir ./${outputFolder}

cd ~