#!/bin/bash

folderPath=$1
sourceFolder=$2

for name in ts gas
do
    inputFolder=${sourceFolder}"/"${name}
    outputFolder=${sourceFolder}"/"${name}"_compiled"

    echo "compile typescript files of folder@"${name}

    cd ~/${folderPath}/${outputFolder}
    rm -f *

    cd ~/${folderPath}/${inputFolder}
pwd
    tsc -p ./
done

cd ~