#!/bin/bash


folderPath="appLab"
thisScript=$(cd $(dirname $0);pwd)/$(basename $0)

scriptFolder="shell"
sourceFolder="src"
distFolder="dist"

tsComplieScript="tsCompile"
distScript="makeDist"
updateAppScript="updateApp"
commitScript="commit"
pullScript="pull"

cd ~/${folderPath}

case $1 in
    --t )
        ./${scriptFolder}/${tsComplieScript} ${folderPath} ${sourceFolder}
        ;;
    --tn )
        ./${scriptFolder}/${tsComplieScript} ${folderPath} ${sourceFolder} --noEmit
        ;;
    --d )
        ./${scriptFolder}/${distScript} ${folderPath} ${sourceFolder} ${distFolder}
        ;;
    --u )
        ./${scriptFolder}/${updateAppScript} ${folderPath}
        ;;
    --c )
        ./${scriptFolder}/${commitScript} ${folderPath} "$2"
        ;;
    --p )
        ./${scriptFolder}/${pullScript} ${folderPath}
        ;;
    --a )
        ${thisScript} --t "$2"
        ${thisScript} --d "$2"
        #${thisScript} --u "$2"
        ${thisScript} --c "$2"
        ;;
    --? )
        echo "The option code("$1") is invalid"
        ;;
    -? )
        echo "The option code("$1") is invalid"
        ;;
    * )
        ${thisScript} --a "$1"
        ;;
esac


