#!/bin/bash

echo "\$1"$1
echo "\$2"$2

folderPath="appLab"
thisScript=$(cd $(dirname $0);pwd)/$(basename $0)

scriptFolder="shell"
sourceFolder="src"
distFolder="dist"

tsComplieScript="tsCompile"
distScript="makeDist"
updateAppScript="updateApp"
commitScript="commit"
pullScript="pull"

cd ~/${folderPath}

case $1 in
    --t )
        ./${scriptFolder}/${tsComplieScript} ${folderPath} ${sourceFolder}
        ;;
    --d )
        ./${scriptFolder}/${distScript} ${folderPath} ${sourceFolder} ${distFolder}
        ;;
    --u )
        ./${scriptFolder}/${updateAppScript} ${folderPath}
        ;;
    --c )
        ./${scriptFolder}/${commitScript} ${folderPath} $2
        ;;
    --p )
        ./${scriptFolder}/${pullScript} ${folderPath}
        ;;
    --a )
        ${thisScript} --t "\"$2\""
        ${thisScript} --d "\"$2\""
        ${thisScript} --u "\"$2\""
        ${thisScript} --c "\"$2\""
        ;;
    * )
        ${thisScript} --a "\"$1\""
        ;;
esac


